const sampleListings = [
  {
    name: "Ahmedabad Blood Bank 1",
    type: "Government Hospital",
    address: "885 Main Road, Ahmedabad, Gujarat",
    distance_km: 3.8,
    phone: "+91 9885799675",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 23,
      "A-": 3,
      "B+": 24,
      "B-": 7,
      "AB+": 0,
      "AB-": 16,
      "O+": 10,
      "O-": 20,
    },
  },
  {
    name: "Vadodara Blood Bank 2",
    type: "Blood Bank",
    address: "773 Main Road, Vadodara, Gujarat",
    distance_km: 4.2,
    phone: "+91 9896556807",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 22,
      "A-": 2,
      "B+": 10,
      "B-": 13,
      "AB+": 24,
      "AB-": 23,
      "O+": 5,
      "O-": 20,
    },
  },
  {
    name: "Anand Blood Bank 3",
    type: "Government Hospital",
    address: "994 Main Road, Anand, Gujarat",
    distance_km: 1.9,
    phone: "+91 9842401867",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 22,
      "A-": 9,
      "B+": 29,
      "B-": 6,
      "AB+": 26,
      "AB-": 21,
      "O+": 7,
      "O-": 25,
    },
  },
  {
    name: "Anand Blood Bank 4",
    type: "Private Hospital",
    address: "904 Main Road, Anand, Gujarat",
    distance_km: 1.4,
    phone: "+91 9857952560",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 15,
      "A-": 12,
      "B+": 25,
      "B-": 16,
      "AB+": 20,
      "AB-": 12,
      "O+": 14,
      "O-": 20,
    },
  },
  {
    name: "Anand Blood Bank 5",
    type: "Private Hospital",
    address: "870 Main Road, Anand, Gujarat",
    distance_km: 1.9,
    phone: "+91 9823905497",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 21,
      "A-": 1,
      "B+": 26,
      "B-": 6,
      "AB+": 21,
      "AB-": 29,
      "O+": 7,
      "O-": 4,
    },
  },
  {
    name: "Gandhinagar Blood Bank 6",
    type: "Private Hospital",
    address: "357 Main Road, Gandhinagar, Gujarat",
    distance_km: 3.3,
    phone: "+91 9892733267",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 21,
      "A-": 12,
      "B+": 5,
      "B-": 26,
      "AB+": 12,
      "AB-": 22,
      "O+": 30,
      "O-": 21,
    },
  },
  {
    name: "Surat Blood Bank 7",
    type: "Government Hospital",
    address: "958 Main Road, Surat, Gujarat",
    distance_km: 2.4,
    phone: "+91 9834399471",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 14,
      "A-": 11,
      "B+": 21,
      "B-": 9,
      "AB+": 25,
      "AB-": 8,
      "O+": 5,
      "O-": 1,
    },
  },
  {
    name: "Vadodara Blood Bank 8",
    type: "Blood Bank",
    address: "650 Main Road, Vadodara, Gujarat",
    distance_km: 0.8,
    phone: "+91 9875863376",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 26,
      "A-": 19,
      "B+": 9,
      "B-": 14,
      "AB+": 16,
      "AB-": 29,
      "O+": 6,
      "O-": 4,
    },
  },
  {
    name: "Vadodara Blood Bank 9",
    type: "Blood Bank",
    address: "830 Main Road, Vadodara, Gujarat",
    distance_km: 2.6,
    phone: "+91 9834797159",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 24,
      "A-": 18,
      "B+": 6,
      "B-": 19,
      "AB+": 10,
      "AB-": 22,
      "O+": 27,
      "O-": 29,
    },
  },
  {
    name: "Gandhinagar Blood Bank 10",
    type: "Blood Bank",
    address: "912 Main Road, Gandhinagar, Gujarat",
    distance_km: 1.0,
    phone: "+91 9872262857",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 21,
      "A-": 19,
      "B+": 6,
      "B-": 18,
      "AB+": 24,
      "AB-": 26,
      "O+": 14,
      "O-": 15,
    },
  },
  {
    name: "Vadodara Blood Bank 11",
    type: "Government Hospital",
    address: "293 Main Road, Vadodara, Gujarat",
    distance_km: 2.7,
    phone: "+91 9894656112",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 24,
      "A-": 11,
      "B+": 10,
      "B-": 12,
      "AB+": 18,
      "AB-": 5,
      "O+": 27,
      "O-": 0,
    },
  },
  {
    name: "Gandhinagar Blood Bank 12",
    type: "Private Hospital",
    address: "767 Main Road, Gandhinagar, Gujarat",
    distance_km: 2.4,
    phone: "+91 9819008876",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 16,
      "A-": 6,
      "B+": 4,
      "B-": 30,
      "AB+": 24,
      "AB-": 7,
      "O+": 30,
      "O-": 9,
    },
  },
  {
    name: "Gandhinagar Blood Bank 13",
    type: "Private Hospital",
    address: "316 Main Road, Gandhinagar, Gujarat",
    distance_km: 2.9,
    phone: "+91 9856545941",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 26,
      "A-": 24,
      "B+": 5,
      "B-": 24,
      "AB+": 1,
      "AB-": 0,
      "O+": 22,
      "O-": 4,
    },
  },
  {
    name: "Surat Blood Bank 14",
    type: "Blood Bank",
    address: "10 Main Road, Surat, Gujarat",
    distance_km: 3.4,
    phone: "+91 9860710864",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 3,
      "A-": 3,
      "B+": 12,
      "B-": 27,
      "AB+": 16,
      "AB-": 19,
      "O+": 25,
      "O-": 11,
    },
  },
  {
    name: "Ahmedabad Blood Bank 15",
    type: "Blood Bank",
    address: "334 Main Road, Ahmedabad, Gujarat",
    distance_km: 4.8,
    phone: "+91 9831706515",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 11,
      "A-": 1,
      "B+": 28,
      "B-": 3,
      "AB+": 12,
      "AB-": 17,
      "O+": 2,
      "O-": 21,
    },
  },
  {
    name: "Anand Blood Bank 16",
    type: "Blood Bank",
    address: "166 Main Road, Anand, Gujarat",
    distance_km: 3.5,
    phone: "+91 9851420300",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 30,
      "A-": 23,
      "B+": 5,
      "B-": 14,
      "AB+": 11,
      "AB-": 0,
      "O+": 6,
      "O-": 20,
    },
  },
  {
    name: "Surat Blood Bank 17",
    type: "Blood Bank",
    address: "472 Main Road, Surat, Gujarat",
    distance_km: 2.3,
    phone: "+91 9834572733",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 28,
      "A-": 12,
      "B+": 10,
      "B-": 17,
      "AB+": 11,
      "AB-": 9,
      "O+": 13,
      "O-": 17,
    },
  },
  {
    name: "Anand Blood Bank 18",
    type: "Blood Bank",
    address: "46 Main Road, Anand, Gujarat",
    distance_km: 4.4,
    phone: "+91 9856890120",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 0,
      "A-": 26,
      "B+": 10,
      "B-": 13,
      "AB+": 23,
      "AB-": 30,
      "O+": 28,
      "O-": 19,
    },
  },
  {
    name: "Vadodara Blood Bank 19",
    type: "Private Hospital",
    address: "944 Main Road, Vadodara, Gujarat",
    distance_km: 3.6,
    phone: "+91 9819039891",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 26,
      "A-": 4,
      "B+": 4,
      "B-": 3,
      "AB+": 28,
      "AB-": 3,
      "O+": 12,
      "O-": 3,
    },
  },
  {
    name: "Anand Blood Bank 20",
    type: "Government Hospital",
    address: "199 Main Road, Anand, Gujarat",
    distance_km: 2.6,
    phone: "+91 9850732604",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 30,
      "A-": 0,
      "B+": 1,
      "B-": 23,
      "AB+": 14,
      "AB-": 16,
      "O+": 19,
      "O-": 28,
    },
  },
  {
    name: "Anand Blood Bank 21",
    type: "Government Hospital",
    address: "257 Main Road, Anand, Gujarat",
    distance_km: 3.1,
    phone: "+91 9821023107",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 11,
      "A-": 28,
      "B+": 19,
      "B-": 22,
      "AB+": 24,
      "AB-": 11,
      "O+": 0,
      "O-": 8,
    },
  },
  {
    name: "Anand Blood Bank 22",
    type: "Blood Bank",
    address: "667 Main Road, Anand, Gujarat",
    distance_km: 4.7,
    phone: "+91 9819929444",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 30,
      "A-": 3,
      "B+": 25,
      "B-": 19,
      "AB+": 18,
      "AB-": 1,
      "O+": 13,
      "O-": 26,
    },
  },
  {
    name: "Gandhinagar Blood Bank 23",
    type: "Private Hospital",
    address: "452 Main Road, Gandhinagar, Gujarat",
    distance_km: 4.9,
    phone: "+91 9849089599",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 14,
      "A-": 2,
      "B+": 25,
      "B-": 5,
      "AB+": 15,
      "AB-": 6,
      "O+": 6,
      "O-": 25,
    },
  },
  {
    name: "Surat Blood Bank 24",
    type: "Private Hospital",
    address: "103 Main Road, Surat, Gujarat",
    distance_km: 2.3,
    phone: "+91 9858759376",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 0,
      "A-": 27,
      "B+": 25,
      "B-": 22,
      "AB+": 1,
      "AB-": 18,
      "O+": 21,
      "O-": 0,
    },
  },
  {
    name: "Surat Blood Bank 25",
    type: "Blood Bank",
    address: "399 Main Road, Surat, Gujarat",
    distance_km: 4.5,
    phone: "+91 9871807300",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 13,
      "A-": 18,
      "B+": 14,
      "B-": 2,
      "AB+": 5,
      "AB-": 13,
      "O+": 1,
      "O-": 18,
    },
  },
  {
    name: "Ahmedabad Blood Bank 26",
    type: "Private Hospital",
    address: "442 Main Road, Ahmedabad, Gujarat",
    distance_km: 1.0,
    phone: "+91 9890262658",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 29,
      "A-": 10,
      "B+": 9,
      "B-": 4,
      "AB+": 27,
      "AB-": 30,
      "O+": 24,
      "O-": 20,
    },
  },
  {
    name: "Ahmedabad Blood Bank 27",
    type: "Blood Bank",
    address: "134 Main Road, Ahmedabad, Gujarat",
    distance_km: 4.6,
    phone: "+91 9831759696",
    timing: "10 AM - 6 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 13,
      "A-": 25,
      "B+": 12,
      "B-": 22,
      "AB+": 23,
      "AB-": 1,
      "O+": 29,
      "O-": 6,
    },
  },
  {
    name: "Ahmedabad Blood Bank 28",
    type: "Blood Bank",
    address: "294 Main Road, Ahmedabad, Gujarat",
    distance_km: 0.7,
    phone: "+91 9885578621",
    timing: "24x7 Emergency",
    status: "Open",
    available_blood_stock: {
      "A+": 0,
      "A-": 28,
      "B+": 29,
      "B-": 20,
      "AB+": 7,
      "AB-": 8,
      "O+": 30,
      "O-": 1,
    },
  },
  {
    name: "Surat Blood Bank 29",
    type: "Blood Bank",
    address: "491 Main Road, Surat, Gujarat",
    distance_km: 5.0,
    phone: "+91 9836827833",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 14,
      "A-": 20,
      "B+": 15,
      "B-": 8,
      "AB+": 30,
      "AB-": 2,
      "O+": 28,
      "O-": 29,
    },
  },
  {
    name: "Vadodara Blood Bank 30",
    type: "Government Hospital",
    address: "422 Main Road, Vadodara, Gujarat",
    distance_km: 1.1,
    phone: "+91 9815411683",
    timing: "9 AM - 8 PM",
    status: "Open",
    available_blood_stock: {
      "A+": 30,
      "A-": 3,
      "B+": 27,
      "B-": 3,
      "AB+": 19,
      "AB-": 14,
      "O+": 29,
      "O-": 29,
    },
  },
];

module.exports = { data: sampleListings };
